print(3 < 5)
print(3 < 5 and 5 < 3)
print(True and False)
print(True or False)
print(not True)
print(not False and True)
print(True and False and True)
print(True or (False and True))
print(False and (5/0 == 1))
print(False and (5/0 == 1))
print(bool(1 and 2))
print(bool(5 and 0))