print(float(4))
print(int(5.3))
print(int(True))
print(float(int(5.3)))
print(float(7) // 4)
print(int(7 / 4))
print(True and 6.2)
print(type(4.5))
print(type(True and 3))
print(0.5 > False)
print(0.5 < False)
print(True and 3)
print(6.2 and False)